passwordGenerator/passGen/urls.py
from django.urls import path
from . import views

app_name = "passGen"
urlpatterns = [
    path('', views.IndexView.index, name='index'),
    path('generate', views.IndexView.generate, name='generate'),
]

passwordGenerator/passwordGenerator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("passGen.urls")),
]

passwordGenerator/passGen/forms.py
from django import forms

class PassForm(forms.Form):
    length = forms.IntegerField(max_value = 94, min_value = 8, required = True, initial = 10)

passwordGenerator/passGen/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .password import PasswordGen
from .forms import PassForm

class IndexView(View):

    def index(request):
        context = {}
        if (request.session.get('password') != ""):
            context['password'] = request.session.get('password')
        if (request.session.get('length') != None):
            context['form'] = PassForm(initial = {'length': request.session.get('length')})
        else:
            context['form'] = PassForm()
        return render(request, 'passGen/index.html', context)

    def generate(request):
        length = 0
        form = PassForm(request.POST or None)
        if request.POST and form.is_valid():
            length = form.cleaned_data.get("length")
        request.session['password'] = PasswordGen(length).generate()
        request.session['length'] = length
        return redirect('/')

passwordGenerator/passGen/templates/passGen/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'passGen/main.css' %}">
        <script type="text/javascript" src="{% static 'passGen/app.js' %}"></script>
        <title>Password Generator</title>
    </head>
    <body>
        <div class="password__box">
            {% if password %}
                <p id="password">{{ password }}</p>
            {% else %}
                <p>Not generated name yet.</p>
            {% endif %}
            <form action="{% url 'passGen:generate' %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <div class="form__button">
                    <button type="submit">Generate password</button>
                    <button onclick="copyToClipboard()">Copy password</button>
                </div>
            </form>
        </div>
    </body>
</html>